version: 2
jobs:
  build:
    docker:
      - image: circleci/node:16-browsers
    working_directory: ~/twilio-video-inspector

    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Installing dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run:
          name: 'Jest Unit Tests'
          command: npm run test:ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: 'test-reports/jest'
            JEST_JUNIT_OUTPUT_NAME: 'results.xml'
            JEST_JUNIT_CLASSNAME: '{classname}'
            JEST_JUNIT_TITLE: '{title}'

      - store_artifacts:
          path: coverage

      - store_test_results:
          path: test-reports

      - run:
          name: 'Eslint'
          command: npm run lint -- --max-warnings 0

      - run:
          name: 'TypeScript'
          command: npm run ts

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
